### ISSUE TITLE
Add a section on the website where we link to all of our sister organizations in other countries

### ISSUE THREAD

**Issue by JorgenLjones** [stiftelsen-effekt/main-site#470] opened 2022-10-13 14:27 UTC
Increase legitimacy, good for SEO, could be useful for some users.

When done, share on #effectivefundraising and encourage the other orgs to do the same

**Comment by fellmirr** [comment] 2023-08-29 10:23
Duplicate of #224 in effekt-admin repo

**Closed by fellmirr** 2023-08-29 10:23 UTC
